const video=document.querySelector('#video');const canvas=document.querySelector('#canvas');const ctx=canvas.getContext('2d');const start=document.querySelector('#start');const filter=document.querySelector('#filter');const status=document.querySelector('#status');const handsLabel=document.querySelector('#hands');const mirror=document.querySelector('#mirror');let camera=null;let running=false;let lastHands=[];let particles=[];
const hands=new Hands({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/hands/${f}`});
hands.setOptions({maxNumHands:2,modelComplexity:1,minDetectionConfidence:.65,minTrackingConfidence:.65});
hands.onResults(results=>{lastHands=results.multiHandLandmarks||[];handsLabel.textContent=`${lastHands.length} hand${lastHands.length===1?'':'s'}`;draw()});
function fit(){if(!video.videoWidth)return;canvas.width=video.videoWidth;canvas.height=video.videoHeight}video.addEventListener('loadedmetadata',fit);window.addEventListener('resize',fit);
start.onclick=async()=>{if(running)return;try{await navigator.mediaDevices.getUserMedia({video:true});camera=new Camera(video,{onFrame:async()=>hands.send({image:video}),width:1280,height:720});camera.start();running=true;start.textContent='Camera Running';status.textContent='Tracking fingertips…'}catch(e){status.textContent='Camera permission denied'}};
mirror.onchange=()=>{video.style.transform=mirror.checked?'scaleX(-1)':'none'};
function P(p){let x=p.x*canvas.width,y=p.y*canvas.height;if(mirror.checked)x=canvas.width-x;return{x,y}}
function lerp(a,b,t){return a+(b-a)*t}function quad(points){const xs=points.map(p=>p.x),ys=points.map(p=>p.y);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}
function getFrame(){const pts=[];for(const hand of lastHands){pts.push(P(hand[8]),P(hand[12]))}if(pts.length<4)return null;return quad(pts)}
function draw(){fit();ctx.clearRect(0,0,canvas.width,canvas.height);if(!lastHands.length)return;const frame=getFrame();const mode=filter.value;drawHands();if(frame&&frame.w>30&&frame.h>30)drawFX(frame,mode);}
function drawHands(){ctx.save();ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#ffffff';ctx.shadowBlur=12;ctx.shadowColor='#00eaff';for(const hand of lastHands){const p=hand.map(P);const chains=[[0,1,2,3,4],[0,5,6,7,8],[0,9,10,11,12],[0,13,14,15,16],[0,17,18,19,20]];for(const c of chains){ctx.beginPath();ctx.moveTo(p[c[0]].x,p[c[0]].y);for(let i=1;i<c.length;i++)ctx.lineTo(p[c[i]].x,p[c[i]].y);ctx.stroke()}for(const i of [4,8,12,16,20]){ctx.beginPath();ctx.arc(p[i].x,p[i].y,7,0,Math.PI*2);ctx.stroke()}}ctx.restore()}
function drawFX(f,mode){const pad=Math.max(10,Math.min(f.w,f.h)*.035);const x=f.x-pad,y=f.y-pad,w=f.w+pad*2,h=f.h+pad*2;ctx.save();ctx.globalCompositeOperation='lighter';if(mode==='rgb'){glitchRect(x,y,w,h,'#ff245b',-7);glitchRect(x,y,w,h,'#16e0ff',7)}else if(mode==='scan'){glitchRect(x,y,w,h,'#fff',0);ctx.globalCompositeOperation='source-over';ctx.strokeStyle='#fff4';ctx.lineWidth=2;for(let yy=y;yy<y+h;yy+=8){ctx.beginPath();ctx.moveTo(x,yy);ctx.lineTo(x+w,yy);ctx.stroke()}}else{glitchRect(x,y,w,h,mode==='neon'?'#00f6ff':'#ffffff',0);for(let i=0;i<10;i++){const yy=y+Math.random()*h;const ww=Math.random()*w*.35;ctx.fillStyle=mode==='neon'?'#00eaff':'#fff';ctx.globalAlpha=.08+Math.random()*.16;ctx.fillRect(x+Math.random()*w,yy,ww,2+Math.random()*5)}}ctx.restore();drawCorner(P(lastHands[0][8]));drawCorner(P(lastHands[0][12]));if(lastHands[1]){drawCorner(P(lastHands[1][8]));drawCorner(P(lastHands[1][12]))}}
function glitchRect(x,y,w,h,color,offset){ctx.strokeStyle=color;ctx.lineWidth=Math.max(3,Math.min(w,h)*.018);ctx.shadowBlur=24;ctx.shadowColor=color;ctx.strokeRect(x+offset,y,w,h);ctx.shadowBlur=0;ctx.fillStyle=color;ctx.globalAlpha=.5;ctx.fillRect(x,y,Math.max(2,w*.01),h);ctx.fillRect(x+w-2,y,2,h)}
function drawCorner(p){ctx.save();ctx.strokeStyle='#fff';ctx.fillStyle='#fff';ctx.shadowBlur=18;ctx.shadowColor='#00eaff';ctx.lineWidth=3;const s=18;ctx.beginPath();ctx.moveTo(p.x-s,p.y);ctx.lineTo(p.x-s,p.y-s);ctx.lineTo(p.x,p.y-s);ctx.moveTo(p.x+s,p.y);ctx.lineTo(p.x+s,p.y+s);ctx.lineTo(p.x,p.y+s);ctx.stroke();ctx.beginPath();ctx.arc(p.x,p.y,4,0,Math.PI*2);ctx.fill();ctx.restore()}
setInterval(()=>{if(!running)return;const f=getFrame();if(!f)return;for(let i=0;i<4;i++)particles.push({x:f.x+Math.random()*f.w,y:f.y+Math.random()*f.h,life:1});if(particles.length>80)particles.splice(0,particles.length-80)},70);
function animate(){if(particles.length){ctx.save();for(const q of particles){q.life-=.035;ctx.globalAlpha=Math.max(0,q.life);ctx.fillStyle='#fff';ctx.fillRect(q.x,q.y,2,2)}particles=particles.filter(q=>q.life>0);ctx.restore()}requestAnimationFrame(animate)}animate();